"""Task texts shared by the deck and video analysis paths."""

# Bump when STUDY_TASK changes so cached study entries from the previous wording are regenerated on retry.
STUDY_CACHE_VERSION = "v4"

AUDIENCE_TASK = """Infer who this lecture is for, using only cues in the lecture itself: the title, course name, section titles and concepts, and the opening minutes of recorded speech (course level, references to earlier classes, assumed background, difficulty of the examples). Return in the output language: level (the learner's stage and where this lecture sits in the course, e.g. first-year undergraduate, first lecture of an introductory course), priorKnowledge (3-8 short items the lecturer assumes the learner already knows), lectureGoal (what the learner should be able to do after this lecture). Do not guess personal details of individual students."""

STUDY_TASK = r"""Create study materials for ONE lecture section in the output language, written for the learner described in `audience`.
- Pitch everything at that level: assume only this lecture's content and the listed prior knowledge; use the lecturer's own notation, terms and examples; never require outside material.
- slideSummary describes what is VISIBLE; spokenSummary describes ONLY the supplied recorded speech; explanation is clearly supplemental teaching that fills the gaps this audience is likely to have.
- Write every equation, symbol and formula in LaTeX in all fields: inline $...$ and display $$...$$.
- Teach theory in this order: a one-sentence plain-language idea, why it is useful, the necessary background, then the formal statement and a small concrete example. Introduce each new term before using it. Use short paragraphs; text fields are plain text with LaTeX, not Markdown headings.
- sourceContext contains the original filename and bounded excerpts of other deck pages, not complete pages. Use these to connect earlier definitions to this section. relatedPages lists only genuinely relevant pages actually supplied in sourceContext, with their topics; never invent page numbers or infer that something is absent from a truncated excerpt.
- For every mathNote, statement preserves the ORIGINAL visible formula/claim and its notation. Populate symbols with the meaning of each symbol (and units/dimensions where relevant), assumptions with when the rule is valid, steps with a motivated derivation (one justified transformation per step), and intuition with an easy interpretation or a small worked numerical example. Start from the simple rule before introducing shorthand.
- Check signs, loss definitions, derivatives, update directions, dimensions and assumptions against the supplied material before teaching a formula. sourceCheck is REQUIRED for math notes: status consistent when the available definitions agree (describe the scope checked, never claim formal verification); corrected only for an error demonstrable from supplied definitions, giving the original conflict, the reason and correctedStatement; uncertain if notation is unreadable, the evidence is incomplete or conventions could explain the difference. With uncertain status, explicitly state what must be checked and do not assert a definitive correction. Never silently rewrite the original. Use a demonstrated correction consistently in subsequent steps, explanation, questions and cards.
- Example of the checking METHOD, not a claim about this lecture: if the source defines E = 1/2(r-y)^2, a linear neuron y=s, delta=r-y and w_j <- w_j + eta*delta*x_j, then delta = -dE/ds. A source also labeling delta as +dE/ds contradicts those definitions. Preserve the original formula, explicitly explain the sign issue, then derive the consistent plus update. Do not apply this example unless these definitions actually occur in the supplied material.
- mathNotes is REQUIRED whenever the section contains any mathematics: one entry per definition, theorem, lemma or formula, AND one entry per worked example (up to six entries, grouping closely related claims if needed). A worked example is any case where the slide or lecturer checks that a concrete object satisfies a definition or computes a result (verifying field or vector-space axioms for R, Q, C, Z_2, Z_4, F^n or matrices, a counterexample, an operation table, solving an equation): kind example, statement = the claim being checked in LaTeX, steps = every condition or computation checked, one per step, with the actual calculation. Give a complete derivation when supported by the supplied definitions and prior knowledge; otherwise explain the missing assumptions rather than fabricating a proof. Set supplementary to true for steps or examples added beyond the lecture. Numbered derivations belong in mathNotes, not only in explanation. Leave mathNotes empty only for sections with no mathematics at all (title, outline, textbook list, break).
- reviewQuestions (2-4): ordered from basic recall, to understanding, to at most one apply question; tag each with difficulty; each must be answerable from this section by this audience, and answers show the working.
- flashcards (2-5): one fact per card; the front is a term or short question, the back a short answer in the lecturer's words.
- For a title, break or reference-only section, return empty lists instead of filler.
- If recorded speech is empty, spokenSummary MUST be empty. If alignment is uncertain, qualify spokenSummary explicitly.
- Suggest 1-2 focused academic-paper search queries (max 200 characters, no private personal information) for substantive concepts, including cited paper titles or DOIs if visible.
- No invented quotations and no claims about exam coverage."""

VIDEO_STUDY_TASK = STUDY_TASK + """
- Video: slideSummary covers the slide, board work, code demo or speaker scene from the actual video observations. If videoMatched is false, never claim the lecturer discussed this slide."""

AUDIO_STUDY_TASK = STUDY_TASK + """
- Audio-only: there are NO slides, images or visual observations. slideSummary is a summary of the audio topic, grounded only in recordedSpeech. Never claim anything was visible or invent original formulas, diagrams or source page numbers. Mathematical notation reconstructed from speech must be marked supplementary and uncertain when ambiguous. relatedPages must be empty."""
